custom:
  enable_rule_generator: false
  overwrite_original_rules: false

  custom_proxy_group:
  - {import: snippets/groups_forcerule.txt}

#  surge_ruleset:
#  - {import: snippets/ruleset_remote.txt}

  clash_rule_base: base/forcerule.yml
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

#  rename_node:
#  - {import: snippet/rename.txt}

#  emoji:
#  - {import: snippets/emoji.txt}

#  include_remarks: []
#  exclude_remarks: []
