[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "rules/MSServices.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "rules/NobyDa/Surge/AdRule.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list"

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/iQiyi.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Letv.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/MOO.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Tencent Video.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Youku.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥ä¿¡æ¯"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/NobyDa/Surge/Download.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

